---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: git@github.com:biparasite/lighthouse.git
    scm: git
    version: "0.1.2"
    name: lighthouse

  - src: git@github.com:biparasite/vector.git
    scm: git
    version: "0.1.0"
    name: vector

